M48
; DRILL file {KiCad (6.0.6)} date Sun Sep  4 20:55:51 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-04T20:55:51+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.6614Y-2.6772
X3.6614Y-4.3425
X5.9409Y-2.6772
X5.9409Y-4.3425
T0
M30
