M48
; DRILL file {KiCad (6.0.6)} date Sat Aug 27 21:29:36 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-27T21:29:36+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.7402Y-2.8346
X3.7402Y-4.8819
X6.2992Y-2.8346
X6.2992Y-4.8819
T0
M30
